import React from "react";
import {
  Activity, BarChart3, Bell, CalendarDays, CheckCircle2, ChevronRight, CircleDollarSign,
  Clock3, FileImage, Filter, FolderOpen, Globe2, LayoutGrid, MapPin, MessageCircle,
  Plus, Search, Send, ShieldCheck, Sparkles, Target, TrendingUp, Upload, Users,
  WalletCards, Zap, Instagram, Youtube, SendHorizontal, CheckSquare, Settings as SettingsIcon
} from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const days = Array.from({ length: 31 }, (_, i) => ({ day: i + 1 }));
const spark = [18, 25, 19, 33, 29, 45, 39, 51, 48, 62, 54, 70];
const leadSeries = Array.from({ length: 31 }, (_, i) => ({ day: `${i + 1} May`, leads: 180 + ((i * 37) % 450), conv: 3 + ((i * 11) % 48) / 10 }));
const palette = ["#0B6BFF", "#18C7A7", "#8B5CF6", "#F59E0B", "#EF4444", "#38BDF8"];
const uzRegions = [
  ["Nukus", 72, 16, 30], ["Urganch", 58, 25, 50], ["Buxoro", 65, 38, 64], ["Navoiy", 74, 45, 40],
  ["Samarqand", 81, 55, 58], ["Qarshi", 60, 62, 72], ["Toshkent", 92, 78, 38], ["Namangan", 70, 88, 34], ["Farg‘ona", 68, 86, 50], ["Andijon", 63, 93, 54]
];

function ProCard({ children, className = "" }) { return <section className={`pro-card ${className}`}>{children}</section>; }
function IconBox({ children, tone = "blue" }) { return <span className={`pro-icon pro-icon-${tone}`}>{children}</span>; }
function Trend({ value = "+12%", good = true }) { return <span className={good ? "pro-trend up" : "pro-trend down"}>{value}</span>; }
function Stat({ title, value, icon, tone = "blue", trend = "+12%", hint = "O‘tgan oyga nisbatan" }) {
  return <ProCard className="pro-stat"><div><IconBox tone={tone}>{icon}</IconBox><p>{title}</p><h3>{value}</h3><Trend value={trend} /></div><MiniSpark /></ProCard>;
}
function MiniSpark() { return <ResponsiveContainer width={95} height={48}><LineChart data={spark.map((v, i) => ({ i, v }))}><Line type="monotone" dataKey="v" stroke="#0B6BFF" strokeWidth={2.4} dot={false} /></LineChart></ResponsiveContainer>; }
function ProHeader({ title, subtitle, action = "Yangi kampaniya" }) {
  return <div className="pro-page-head"><div><h1>{title}</h1>{subtitle ? <p>{subtitle}</p> : null}</div><div className="pro-top-controls"><label className="pro-search"><Search size={17}/><input placeholder="Qidirish... (lidlar, kampaniya, kontent...)"/><kbd>⌘ K</kbd></label><button className="pro-date">01 May – 31 May 2025</button><button className="pro-bell"><Bell size={18}/><b>6</b></button><button className="pro-primary"><Plus size={18}/>{action}</button></div></div>;
}
function ProShell({ title, subtitle, children, action }) { return <div className="pro-screen"><ProHeader title={title} subtitle={subtitle} action={action}/>{children}</div>; }
function SmallTable({ rows }) { return <div className="pro-table"><table><tbody>{rows.map((r, i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>; }

export default function ProPage({ page = "dashboard" }) {
  if (page === "content") return <ContentCalendar />;
  if (page === "campaigns") return <CampaignCenter />;
  if (page === "uploads") return <MediaLibrary />;
  if (page === "tasks") return <Workflow />;
  if (page === "bonus") return <KpiBonus />;
  if (page === "analytics") return <BranchMap />;
  if (page === "expenses" || page === "finance") return <Finance />;
  if (page === "travelPlans") return <ChatApproval />;
  if (page === "settings") return <SettingsSecurity />;
  if (page === "users") return <People />;
  return <Dashboard />;
}

function Dashboard(){
  return <ProShell title="Boshqaruv markazi" subtitle="aloo SMM jamoasi uchun real-time nazorat va strategik markaz">
    <div className="pro-stats five"><Stat title="Yangi lidlar" value="4,832" icon={<Users size={20}/>} tone="blue" trend="↑ 18.6%"/><Stat title="CPL o‘rtacha" value="18,420 so‘m" icon={<Target size={20}/>} tone="cyan" trend="↓ 6.3%"/><Stat title="Konversiya" value="7.48%" icon={<Activity size={20}/>} tone="violet" trend="↑ 1.12%"/><Stat title="Sotuvga ta’sir" value="3.21 mlrd" icon={<TrendingUp size={20}/>} tone="green" trend="↑ 24.7%"/><Stat title="Jamoa produktivligi" value="86%" icon={<Zap size={20}/>} tone="amber" trend="↑ 8%"/></div>
    <div className="pro-grid-main"><ProCard className="pro-big-chart"><div className="pro-card-head"><h2>Lidlar dinamikasi</h2><button>Eksport</button></div><ResponsiveContainer width="100%" height={315}><BarChart data={leadSeries}><CartesianGrid strokeDasharray="3 3" stroke="#E6EDF7"/><XAxis dataKey="day" tick={{fontSize:11}} interval={5}/><YAxis/><Tooltip/><Bar dataKey="leads" radius={[8,8,0,0]} fill="#0B6BFF"/><Line type="monotone" dataKey="conv" stroke="#7C3AED" strokeWidth={2}/></BarChart></ResponsiveContainer></ProCard>
    <ProCard><div className="pro-card-head"><h2>Kampaniyalar samaradorligi</h2><a>Barchasi →</a></div><SmallTable rows={[[<><Instagram size={18}/> May aksiya</>,"1,248","15,230 so‘m","8.12%"],[<><Globe2 size={18}/> Google Search</>,"987","21,450 so‘m","6.23%"],[<><SendHorizontal size={18}/> Telegram</>,"623","12,870 so‘m","9.11%"],[<><Youtube size={18}/> YouTube</>,"542","17,980 so‘m","5.67%"]]}/></ProCard>
    <ProCard><h2>Kontent holati</h2><Donut labels={["Tasdiqlangan", "Ko‘rib chiqilmoqda", "O‘zgartirish kerak", "Rad etilgan"]}/></ProCard></div>
    <div className="pro-grid-4"><MiniMap/><ApprovalQueue/><Upcoming/><ActivityFeed/></div>
  </ProShell>
}

function Donut({ labels }){ const data=[128,36,18,9].map((value,i)=>({name:labels[i], value})); return <div className="pro-donut"><ResponsiveContainer width={130} height={130}><PieChart><Pie data={data} innerRadius={42} outerRadius={62} dataKey="value">{data.map((_,i)=><Cell key={i} fill={palette[i]}/>)}</Pie></PieChart></ResponsiveContainer><div>{data.map((d,i)=><p key={d.name}><i style={{background:palette[i]}}/> {d.name}<b>{d.value}</b></p>)}</div></div> }
function MiniMap(){ return <ProCard><div className="pro-card-head"><h2>Filiallar bo‘yicha natija</h2><a>Barchasi →</a></div><div className="uz-map">{uzRegions.slice(0,6).map(([n,v,x,y])=><span key={n} style={{left:`${x}%`,top:`${y}%`}}>{v}</span>)}</div><SmallTable rows={[["Toshkent","1,842"],["Samarqand","687"],["Farg‘ona","512"]]}/></ProCard> }
function ApprovalQueue(){ return <ProCard><div className="pro-card-head"><h2>Tasdiqlash navbati</h2><b className="badge red">7</b></div>{["May aksiya posti","Yangi banner dizayn","Telegram post – chegirma"].map((t,i)=><div className="approval-item" key={t}><div className="thumb"/><div><b>{t}</b><p>{i?"O‘zgartirish kerak":"Ko‘rib chiqish"}</p></div><span>{2+i*2} soat</span></div>)}</ProCard> }
function Upcoming(){ return <ProCard><h2>Kelayotgan vazifalar</h2>{["May hisobotini tayyorlash","Kampaniya natijalarini tahlil qilish","Kontent rejasini tasdiqlash","Google Ads byudjetini yangilash"].map((t,i)=><div className="task-line" key={t}><CheckCircle2 size={18}/><span>{t}</span><b>{i===0?"Bugun":`${i+1} Iyun`}</b></div>)}</ProCard> }
function ActivityFeed(){ return <ProCard><h2>Jamoa faolligi</h2>{["Malika yangi kampaniya yaratdi","Islom kontent yubordi","Nodira lid manbasini o‘zgartirdi","Behzod hisobot eksport qildi"].map((t,i)=><div className="feed" key={t}><span className="avatar">{i+1}</span><p>{t}<small>10:{24-i*7}</small></p></div>)}</ProCard> }

function ContentCalendar(){return <ProShell title="Kontent kalendari" subtitle="Kontent rejalash, tasdiqlash va chop etish jarayoni" action="Kontent qo‘shish"><div className="pro-stats five"><Stat title="Jami kontent" value="152" icon={<FileImage size={20}/>}/><Stat title="Rejalashtirilgan" value="68" icon={<CalendarDays size={20}/>} tone="green"/><Stat title="Chop etilgan" value="54" icon={<CheckCircle2 size={20}/>} tone="cyan"/><Stat title="Tasdiqlanishda" value="18" icon={<Clock3 size={20}/>} tone="amber"/><Stat title="Bekor qilingan" value="12" icon={<Filter size={20}/>} tone="red"/></div><div className="calendar-layout"><ProCard className="calendar-card"><div className="pro-card-head"><h2>May 2025</h2><div className="seg"><b>Oy</b><span>Hafta</span><span>Kun</span></div></div><div className="calendar-grid"><b>Du</b><b>Se</b><b>Ch</b><b>Pa</b><b>Ju</b><b>Sh</b><b>Ya</b>{days.map((d,i)=><div className="cal-day" key={d.day}><strong>{d.day}</strong>{[1,2,5,7,9,14,16,21,24,28,30].includes(d.day)?<em><Instagram size={12}/> {i%2?"Mijoz fikri":"Aksiya posti"}</em>:null}{[3,8,14,20,29].includes(d.day)?<em className="yt"><Youtube size={12}/> Shorts video</em>:null}</div>)}</div></ProCard><div className="side-stack"><ProCard><h2>Kontent pipeline</h2>{["G‘oya 24","Rejalashtirilgan 68","Tasdiqlanishda 18","Chop etilgan 54","Bekor qilingan 12"].map(x=><p className="pipe" key={x}>{x}</p>)}</ProCard><ProCard><h2>Haftalik agenda</h2>{["09:30 Mijoz fikri","14:30 Shorts video","11:00 Blog post","15:00 Q&A sessiya"].map(x=><div className="task-line" key={x}><Clock3 size={16}/><span>{x}</span></div>)}</ProCard></div><ProCard className="detail-drawer"><div className="pro-card-head"><h2>Mijoz fikri</h2><b className="badge amber">Tasdiqlanishda</b></div><div className="media-preview">aloo yordamida produktivlik 2 baravar oshdi!</div><p className="muted">Aloo platformasi bizning ish jarayonlarimizni butunlay o‘zgartirdi.</p><SmallTable rows={[["Kampaniya","aloo brend kampaniyasi"],["Muallif","Malika Abdullayeva"],["Mas’ul","Sardor Karimov"],["Muddat","13 May, 18:00"]]}/><button className="pro-primary wide">Tasdiqlash</button></ProCard></div></ProShell>}

function CampaignCenter(){return <ProShell title="Kampaniyalar markazi" subtitle="Reklama, CPL, ROI va filial targetlash boshqaruvi"><div className="pro-stats five"><Stat title="Sarflangan byudjet" value="128.54 mln" icon={<WalletCards size={20}/>}/><Stat title="Olingan lidlar" value="4,832" icon={<Users size={20}/>} tone="green"/><Stat title="O‘rtacha CPL" value="18,420 so‘m" icon={<Target size={20}/>} tone="cyan"/><Stat title="Konversiya" value="7.48%" icon={<Activity size={20}/>} tone="violet"/><Stat title="ROI" value="342%" icon={<TrendingUp size={20}/>} tone="amber"/></div><div className="pro-grid-main"><ProCard><h2>Kampaniyalar samaradorligi</h2><SmallTable rows={[["Yozgi chegirmalar 2025","Meta","31.2 mln","1,248","312%",<b className="badge green">Faol</b>],["aloo Premium Launch","Google","20.1 mln","987","298%",<b className="badge green">Faol</b>],["Telegram awareness","Telegram","12.8 mln","623","220%",<b className="badge amber">Pauza</b>],["Influencer hamkorlik","Influencer","17.9 mln","542","185%",<b className="badge green">Faol</b>]]}/></ProCard><ProCard><h2>Kanal bo‘yicha taqqoslash</h2>{["Meta Ads","Google Ads","Telegram Ads","Influencer"].map((x,i)=><div className="bar-row" key={x}><span>{x}</span><i style={{width:`${90-i*13}%`,background:palette[i]}}/><b>{305-i*35}%</b></div>)}</ProCard><ProCard><h2>Byudjet taqsimoti</h2><Donut labels={["Meta Ads","Google Ads","Telegram","Influencer"]}/></ProCard></div><div className="campaign-cards">{["Yozgi chegirmalar 2025","aloo Premium Launch","Telegram awareness","Influencer hamkorlik","Retargeting"].map((x,i)=><ProCard key={x}><h3>{x}</h3><p>{["Meta Ads","Google Ads","Telegram Ads","Influencer","Meta Ads"][i]}</p><b>{[89,81,72,90,60][i]}%</b><div className="progress"><i style={{width:`${[89,81,72,90,60][i]}%`}}/></div></ProCard>)}</div></ProShell>}
function MediaLibrary(){return <ProShell title="Media kutubxonasi" subtitle="Media aktivlar, bannerlar, video va shablonlar markazi" action="Yuklash"><div className="pro-stats four"><Stat title="Umumiy xotira" value="68.4 GB" icon={<FolderOpen size={20}/>}/><Stat title="Fayllar soni" value="1,248" icon={<FileImage size={20}/>} tone="blue"/><Stat title="Formatlar" value="9 tur" icon={<LayoutGrid size={20}/>} tone="violet"/><Stat title="O‘rtacha o‘lcham" value="54.8 MB" icon={<Upload size={20}/>} tone="amber"/></div><div className="media-layout"><ProCard className="collection"><h2>Kolleksiyalar</h2>{["Barchasi 1,248","Bannerlar 342","Post vizuallar 428","Reels muqovalari 156","Filial fotosuratlari 198","Videolar 76"].map(x=><p key={x}>{x}</p>)}</ProCard><div className="media-grid">{Array.from({length:9},(_,i)=><ProCard className="asset" key={i}><div className={`asset-img a${i%5}`}>{i%3===0?"Yozgi chegirmalar boshlandi!":i%3===1?"aloo super app":"Ramazon Muborak"}</div><h3>{["banner_yoz_chegirma.png","post_super_app.jpg","ramazon_post.jpg"][i%3]}</h3><p>{(1.2+i/2).toFixed(1)} MB • {i%4===0?"PSD":i%3===0?"PNG":"JPG"}</p><b className="badge green">Approved</b></ProCard>)}</div><ProCard className="detail-drawer"><h2>Fayl tafsilotlari</h2><div className="asset-img a0">Yozgi chegirmalar</div><SmallTable rows={[["Format","PNG"],["O‘lcham","1920 × 1080"],["Yuklagan","Malika"],["Status","Approved"],["Versiya","v2"]]}/><button className="pro-primary wide">Yuklab olish</button></ProCard></div></ProShell>}
function Workflow(){ const cols=["Rejada","Jarayonda","Tekshiruvda","Tayyor"]; return <ProShell title="Vazifalar va workflow" subtitle="Jamoa vazifalari, sprint va workflow nazorati" action="Vazifa yaratish"><div className="workflow-layout"><div className="kanban">{cols.map((c,ci)=><ProCard className="kanban-col" key={c}><div className="pro-card-head"><h2>{c}</h2><Plus size={16}/></div>{["Landing page dizaynini yangilash","SEO blog sahifalari","Yangi API hujjatlash","Mobil tugmalar stilini moslashtirish"].map((t,i)=><div className="task-card" key={t}><h3>{ci===1?"Foydalanuvchi rol va ruxsatlar tizimi":ci===2?"To‘lov tizimi integratsiyasi":ci===3?"Dashboard filtrlar":t}</h3><p>aloo Platform</p><span className="avatars"><i/><i/><i/></span><b className={`badge ${i%2?"green":"amber"}`}>{i%2?"Past":"O‘rta"}</b><div className="progress"><i style={{width:`${ci*25+i*8}%`}}/></div></div>)}</ProCard>)}</div><div className="side-stack"><ProCard><h2>Jamoa yuklamasi</h2>{["Sardor 85%","Malika 70%","Islom 65%","Nozira 40%"].map(x=><div className="bar-row" key={x}><span>{x}</span><i/><b></b></div>)}</ProCard><ProCard><h2>Sprint 12</h2><Donut labels={["Tayyor","Jarayonda","Qolgan","" ]}/><button className="pro-primary wide">Vazifa yaratish</button></ProCard></div></div></ProShell>}
function KpiBonus(){return <ProShell title="KPI va bonus" subtitle="Jamoa samaradorligi, maqsadlar va rag‘batlantirish" action="Maqsad qo‘shish"><div className="pro-stats four"><Stat title="Umumiy KPI" value="78.4%" icon={<BarChart3 size={20}/>}/><Stat title="Maqsad bajarilish" value="86.2%" icon={<Target size={20}/>} tone="green"/><Stat title="Jami bonus fondi" value="120.45 mln" icon={<CircleDollarSign size={20}/>} tone="violet"/><Stat title="To‘langan bonus" value="85.75 mln" icon={<WalletCards size={20}/>} tone="green"/></div><div className="pro-grid-main"><ProCard><h2>KPI ko‘rsatkichlari</h2><div className="gauge-row">{[82,76,89,68].map((v,i)=><div className="gauge" key={v}><span>{v}%</span><p>{["Lidlar","Konversiya","Sotuv","Faollik"][i]}</p></div>)}</div></ProCard><ProCard><h2>Top liderlar</h2><SmallTable rows={[["1 Malika", "92.4%", "4.25 mln"],["2 Islom", "88.1%", "3.75 mln"],["3 Nodira", "85.6%", "3.25 mln"],["4 Behzod", "82.3%", "2.85 mln"]]}/></ProCard><ProCard><h2>Bonus qoidalari</h2>{["Maqsad bajarilishiga qarab","Konversiya asosida","Faollik indeksi","Jamoaviy bonus"].map(x=><p className="pipe" key={x}>{x}</p>)}</ProCard></div><ProCard><h2>Xodimlar jadvali</h2><SmallTable rows={[["Malika Abdullayeva","Marketing","92.4%","104%","4,250,000 so‘m"],["Islom Ibragimov","Savdo","88.1%","98%","3,750,000 so‘m"],["Nodira Sultanova","Qo‘llab-quvvatlash","85.6%","95%","3,250,000 so‘m"]]}/></ProCard></ProShell>}
function BranchMap(){return <ProShell title="Filiallar xaritasi" subtitle="Hududlar bo‘yicha filiallar samaradorligi"><div className="branch-layout"><ProCard className="big-map-card"><div className="filter-row"><button>Barcha viloyatlar</button><button>KPI: Daromad</button><button>Filterlarni tozalash</button></div><div className="uz-map big">{uzRegions.map(([n,v,x,y])=><span key={n} style={{left:`${x}%`,top:`${y}%`}}><b>{v}</b><small>{n}</small></span>)}</div></ProCard><ProCard className="detail-drawer"><div className="city-photo">Toshkent</div><h2>Toshkent filiali</h2><b className="badge green">Samaradorlik 92</b><SmallTable rows={[["Daromad ta’siri","5,420"],["Leadlar","1,248"],["Konversiya","8.12%"],["Menejer","Azizbek Mirzayev"]]}/><button className="pro-primary wide">Hisobotga o‘tish</button></ProCard></div><div className="pro-stats five"><Stat title="Daromad ta’siri" value="18,420" icon={<TrendingUp size={20}/>} tone="green"/><Stat title="Leadlar" value="4,832" icon={<Users size={20}/>}/><Stat title="Konversiya" value="7.48%" icon={<Target size={20}/>} tone="violet"/><Stat title="Kontent faolligi" value="3.21" icon={<Activity size={20}/>} tone="amber"/><Stat title="Xodimlar indeksi" value="86%" icon={<ShieldCheck size={20}/>} tone="green"/></div><ProCard><h2>Filiallar ro‘yxati</h2><SmallTable rows={[["Toshkent filiali","Toshkent sh.","92","5,420","1,248","8.12%"],["Samarqand filiali","Samarqand","81","2,845","687","7.65%"],["Navoiy filiali","Navoiy","74","1,986","512","6.92%"],["Namangan filiali","Namangan","70","1,452","401","6.21%"]]}/></ProCard></ProShell>}
function Finance(){return <ProShell title="Moliya va xarajatlar" subtitle="Xarajatlar nazorati, byudjet va moliyaviy tahlillar" action="Qo‘shish"><div className="pro-stats four"><Stat title="Jami xarajatlar" value="128.45 mln" icon={<WalletCards size={20}/>} trend="↓ 8.2%"/><Stat title="Byudjet bajarilishi" value="86.3%" icon={<Target size={20}/>} tone="green"/><Stat title="Tasdiqlangan" value="97.2 mln" icon={<CheckSquare size={20}/>} tone="violet"/><Stat title="Qaytish kutilmoqda" value="21.25 mln" icon={<CircleDollarSign size={20}/>} tone="amber"/></div><div className="finance-layout"><ProCard className="pro-big-chart"><h2>Xarajatlar dinamikasi</h2><ResponsiveContainer width="100%" height={280}><BarChart data={leadSeries}><CartesianGrid stroke="#E6EDF7"/><XAxis dataKey="day" interval={5}/><YAxis/><Tooltip/><Bar dataKey="leads" fill="#0B6BFF" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></ProCard><ProCard><h2>Byudjet taqsimoti</h2><Donut labels={["Kontent","Reklama","Xodimlar","Safarlar"]}/></ProCard><ProCard className="form-card"><h2>Yangi xarajat qo‘shish</h2>{["Xarajat turi","Kategoriya","Summa","Sana","To‘lov usuli"].map(x=><label key={x}><span>{x}</span><input placeholder="Tanlang"/></label>)}<button className="pro-primary wide">Qo‘shish</button></ProCard></div><ProCard><h2>Xarajatlar ro‘yxati</h2><SmallTable rows={[["31.05.2025","Instagram kontent suratga olish","8,500,000",<b className="badge green">Tasdiqlangan</b>],["30.05.2025","Facebook reklama byudjeti","12,750,000",<b className="badge amber">Kutilmoqda</b>],["29.05.2025","Dizayner oylik maoshi","6,000,000",<b className="badge green">Tasdiqlangan</b>]]}/></ProCard></ProShell>}
function ChatApproval(){return <ProShell title="Chat va tasdiqlash" subtitle="Ichki suhbat, fayl versiyalari va tasdiqlash workflow"><div className="chat-layout"><ProCard className="chat-list"><h2>Suhbatlar</h2>{["Instagram kampaniya","Website kontent yangilanishi","YouTube video tasdiqlash","Telegram post – chegirma","Google Ads kampaniya"].map((x,i)=><div className="chat-row" key={x}><span className="avatar">{i+1}</span><div><b>{x}</b><p>Yangi dizayn tayyor...</p></div><em>{i?"09:58":"10:30"}</em></div>)}</ProCard><ProCard className="chat-thread"><h2>Instagram kampaniya</h2><div className="msg"><b>Kamoliddin A.</b><p>Yangi banner dizayni tayyor, tasdiqlash uchun yuboraman.</p><div className="file-chip">banner_v3_final.jpg</div></div><div className="msg mine"><b>Sardor Karimov</b><p>Zo‘r ko‘rinibdi! Matnni biroz qisqartirishni tavsiya qilaman.</p></div><div className="msg"><b>Malika Abdullayeva</b><p>Yangi variantni yukladim.</p><div className="file-chip">banner_v3_final_v2.jpg</div></div><label className="message-box"><input placeholder="Xabar yozing..."/><button><Send size={18}/></button></label></ProCard><ProCard className="detail-drawer"><h2>Tasdiqlash obyekti</h2><div className="media-preview">Instagram banner</div><b className="badge amber">Ko‘rib chiqilmoqda</b><div className="approval-steps"><i/><i/><i/><i/></div><button className="pro-primary wide">Tasdiqlash</button><button className="outline wide">O‘zgartirish so‘rash</button></ProCard></div></ProShell>}
function SettingsSecurity(){return <ProShell title="Sozlamalar va xavfsizlik" subtitle="Hisob, ruxsatlar, xavfsizlik va integratsiyalar"><div className="settings-grid"><ProCard><h2>Hisob sozlamalari</h2><div className="profile-mini"><span className="avatar big">S</span><div><h3>Sardor Karimov</h3><p>Administrator</p></div></div><SmallTable rows={[["Email","sardor.karimov@aloo.uz"],["Telefon","+998 90 123 45 67"],["Til","O‘zbekcha"],["Vaqt mintaqasi","Asia/Tashkent"]]}/></ProCard><ProCard><h2>Rollar va ruxsatlar</h2><div className="permission-matrix">{["Lidlar","Kampaniyalar","Kontent","Statistikalar","Xodimlar","Moliya","Sozlamalar"].map(x=><p key={x}><span>{x}</span><input type="checkbox" checked readOnly/><input type="checkbox" checked={x!=="Xodimlar"} readOnly/><input type="checkbox" checked={x!=="Statistikalar"} readOnly/><input type="checkbox" readOnly/></p>)}</div></ProCard><ProCard><h2>Filiallarga kirish</h2>{["Toshkent markaziy","Samarqand filiali","Farg‘ona filiali","Andijon filiali","Buxoro filiali"].map((x,i)=><div className="task-line" key={x}><MapPin size={16}/><span>{x}</span><b className={i===4?"badge gray":"badge green"}>{i===4?"Nofaol":"Aktiv"}</b></div>)}</ProCard><ProCard><h2>Xavfsizlik holati</h2><div className="gauge"><span>85%</span><p>Yaxshi</p></div>{["Email tasdiqlangan","2FA yoqilgan","Kuchli parol","Faol seanslar tekshirildi"].map(x=><p className="pipe" key={x}>✓ {x}</p>)}</ProCard></div></ProShell>}
function People(){return <ProShell title="Xodimlar markazi" subtitle="Jamoa, rollar, vazifalar va faoliyat boshqaruvi" action="Xodim qo‘shish"><div className="pro-stats four"><Stat title="Jami xodim" value="24" icon={<Users size={20}/>}/><Stat title="Faol" value="21" icon={<Activity size={20}/>} tone="green"/><Stat title="Bugun online" value="12" icon={<Bell size={20}/>} tone="cyan"/><Stat title="O‘rtacha KPI" value="78.4%" icon={<BarChart3 size={20}/>} tone="violet"/></div><ProCard><h2>Xodimlar ro‘yxati</h2><SmallTable rows={[["Malika Abdullayeva","Marketing","UI/UX Designer","92.4%",<b className="badge green">Faol</b>],["Islom Ibragimov","Savdo","Backend Developer","88.1%",<b className="badge green">Faol</b>],["Nodira Sultanova","Support","QA Engineer","85.6%",<b className="badge green">Faol</b>],["Behzod Nematov","DevOps","DevOps Engineer","82.3%",<b className="badge amber">Band</b>]]}/></ProCard></ProShell>}
