import { useEffect, useState } from 'react';
import { Save, UserPlus, X } from 'lucide-react';

const emptyForm = { fullName:'',login:'',phone:'',email:'',password:'',role:'viewer',jobTitle:'',avatarUrl:'',telegramUsername:'',notes:'',isActive:true,branchIds:[],primaryBranchId:'' };
function toForm(item){ if(!item)return emptyForm; return { fullName:item.fullName||'',login:item.login||'',phone:item.phone||'',email:item.email||'',password:'',role:item.role||'viewer',jobTitle:item.jobTitle||'',avatarUrl:item.avatarUrl||'',telegramUsername:item.telegramUsername||'',notes:item.notes||'',isActive:item.isActive!==false,branchIds:(item.branches||[]).map((b)=>Number(b.id)),primaryBranchId:(item.branches||[]).find((b)=>b.isPrimary)?.id||'' }; }
export default function TeamFormModal({open,item,roles,branches,saving,currentUser,onClose,onSave}){
  const [form,setForm]=useState(emptyForm); const [error,setError]=useState('');
  useEffect(()=>{if(open){setForm(toForm(item));setError('');}},[open,item]); if(!open)return null;
  const change=(key,value)=>setForm((current)=>({...current,[key]:value}));
  const toggleBranch=(id)=>{const branchIds=form.branchIds.includes(id)?form.branchIds.filter((x)=>x!==id):[...form.branchIds,id];change('branchIds',branchIds);if(!branchIds.includes(Number(form.primaryBranchId)))change('primaryBranchId',branchIds[0]||'');};
  const submit=async(e)=>{e.preventDefault();if(form.fullName.trim().length<2)return setError('Xodim ism-familiyasini kiriting.');if(form.login.trim().length<2)return setError('Loginni kiriting.');if(!item&&form.password.length<6)return setError('Parol kamida 6 ta belgidan iborat bo‘lsin.');setError('');await onSave(form);};
  return <div className="modal-backdrop" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="content-modal team-modal" onSubmit={submit}><header className="modal-header"><div><span className="modal-icon"><UserPlus size={21}/></span><div><h2>{item?'Xodimni tahrirlash':'Yangi xodim'}</h2><p>Profil, rol va filial biriktirish</p></div></div><button type="button" className="icon-button" onClick={onClose}><X size={21}/></button></header><div className="form-grid organization-form-grid">
    <label className="form-field"><span>Ism-familiya</span><input value={form.fullName} onChange={(e)=>change('fullName',e.target.value)} placeholder="Azizbek Karimov"/></label><label className="form-field"><span>Lavozim</span><input value={form.jobTitle} onChange={(e)=>change('jobTitle',e.target.value)} placeholder="SMM menejer"/></label>
    <label className="form-field"><span>Login</span><input value={form.login} onChange={(e)=>change('login',e.target.value)} placeholder="azizbek"/></label><label className="form-field"><span>{item?'Yangi parol (ixtiyoriy)':'Parol'}</span><input type="password" value={form.password} onChange={(e)=>change('password',e.target.value)} placeholder={item?'O‘zgartirmaslik uchun bo‘sh qoldiring':'Kamida 6 ta belgi'}/></label>
    <label className="form-field"><span>Telefon</span><input value={form.phone} onChange={(e)=>change('phone',e.target.value)} placeholder="+998 90 000 00 00"/></label><label className="form-field"><span>Email</span><input type="email" value={form.email} onChange={(e)=>change('email',e.target.value)} placeholder="name@aloo.uz"/></label>
    <label className="form-field"><span>Telegram username</span><input value={form.telegramUsername} onChange={(e)=>change('telegramUsername',e.target.value)} placeholder="@username"/></label><label className="form-field"><span>Rol</span><select value={form.role} onChange={(e)=>change('role',e.target.value)}>{roles.filter((role)=>role.code!=='admin'||currentUser?.role==='admin').map((role)=><option key={role.code} value={role.code}>{role.name}</option>)}</select></label>
    <div className="form-field form-field--wide"><span>Filiallar</span><div className="organization-choice-grid">{branches.map((branch)=><button type="button" key={branch.id} className={form.branchIds.includes(Number(branch.id))?'active':''} onClick={()=>toggleBranch(Number(branch.id))}>{branch.name}</button>)}</div></div>
    {form.branchIds.length>0&&<label className="form-field form-field--wide"><span>Asosiy filial</span><select value={form.primaryBranchId} onChange={(e)=>change('primaryBranchId',Number(e.target.value))}>{branches.filter((branch)=>form.branchIds.includes(Number(branch.id))).map((branch)=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label>}
    <label className="form-field form-field--wide"><span>Izoh</span><textarea rows={3} value={form.notes} onChange={(e)=>change('notes',e.target.value)} placeholder="Xodim vazifalari yoki qo‘shimcha ma’lumot..."/></label>
    <label className="organization-switch form-field--wide"><input type="checkbox" checked={form.isActive} onChange={(e)=>change('isActive',e.target.checked)}/><span/><div><strong>Foydalanuvchi faol</strong><small>Faol foydalanuvchi tizimga kira oladi</small></div></label>
  </div>{error&&<div className="form-error modal-error">{error}</div>}<footer className="modal-actions"><button type="button" className="button-ghost" onClick={onClose}>Bekor qilish</button><button className="button-primary" disabled={saving}><Save size={18}/>{saving?'Saqlanmoqda...':'Saqlash'}</button></footer></form></div>;
}
