import { useEffect, useMemo, useState } from 'react';
import { Bell, Building2, Check, Eye, EyeOff, KeyRound, MonitorCog, Palette, Save, ShieldCheck, UserRound } from 'lucide-react';
import { apiRequest, authHeaders } from '../lib/api.js';

const emptyProfile = { fullName: '', login: '', phone: '', email: '', jobTitle: '', avatarUrl: '', telegramUsername: '' };
const defaultPrefs = { language: 'uz', timezone: 'Asia/Tashkent', dateFormat: 'DD.MM.YYYY', compactMode: false, soundEnabled: true, desktopEnabled: true, chatNotifications: true, taskNotifications: true, contentNotifications: true, expenseNotifications: true, reportNotifications: true };
const defaultCompany = { companyName: 'aloo SMM Panel', domain: 'aloosmm.uz', supportPhone: '', supportTelegram: '', timezone: 'Asia/Tashkent', currency: 'UZS', brandColor: '#1690F5', defaultLanguage: 'uz' };
const initials = (name = '') => name.split(/\s+/).filter(Boolean).map((part) => part[0]).join('').slice(0, 2).toUpperCase();

function Toggle({ checked, onChange, label, description }) {
  return <label className="settings-toggle"><span><strong>{label}</strong><small>{description}</small></span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><i /></label>;
}

export default function SettingsPage({ session, notify, onUserUpdated }) {
  const [tab, setTab] = useState('profile');
  const [profile, setProfile] = useState(emptyProfile);
  const [prefs, setPrefs] = useState(defaultPrefs);
  const [company, setCompany] = useState(defaultCompany);
  const [system, setSystem] = useState(null);
  const [password, setPassword] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' });
  const [showPasswords, setShowPasswords] = useState(false);
  const [saving, setSaving] = useState('');
  const headers = useMemo(() => authHeaders(session.token), [session.token]);
  const canManage = session.user?.role === 'admin' || session.user?.permissions?.includes('settings.manage');

  useEffect(() => {
    const requests = [apiRequest('/api/settings/profile', { headers }), apiRequest('/api/settings/preferences', { headers })];
    if (canManage) requests.push(apiRequest('/api/settings/company', { headers }), apiRequest('/api/settings/system', { headers }));
    Promise.all(requests).then((results) => {
      setProfile({ ...emptyProfile, ...(results[0].profile || {}) });
      setPrefs({ ...defaultPrefs, ...(results[1].preferences || {}) });
      if (canManage) { setCompany({ ...defaultCompany, ...(results[2].company || {}) }); setSystem(results[3] || null); }
    }).catch((error) => notify(error.message));
  }, [headers, canManage]);

  const saveProfile = async (event) => {
    event.preventDefault(); setSaving('profile');
    try { const result = await apiRequest('/api/settings/profile', { method: 'PUT', headers, body: JSON.stringify(profile) }); onUserUpdated(result.user); notify('Profil ma’lumotlari saqlandi.'); }
    catch (error) { notify(error.message); } finally { setSaving(''); }
  };
  const savePassword = async (event) => {
    event.preventDefault();
    if (password.newPassword !== password.confirmPassword) return notify('Yangi parollar bir xil emas.');
    setSaving('password');
    try { await apiRequest('/api/settings/password', { method: 'PUT', headers, body: JSON.stringify({ currentPassword: password.currentPassword, newPassword: password.newPassword }) }); setPassword({ currentPassword: '', newPassword: '', confirmPassword: '' }); notify('Parol muvaffaqiyatli yangilandi.'); }
    catch (error) { notify(error.message); } finally { setSaving(''); }
  };
  const savePrefs = async () => { setSaving('prefs'); try { const result = await apiRequest('/api/settings/preferences', { method: 'PUT', headers, body: JSON.stringify(prefs) }); setPrefs({ ...defaultPrefs, ...result.preferences }); notify('Shaxsiy sozlamalar saqlandi.'); } catch (error) { notify(error.message); } finally { setSaving(''); } };
  const saveCompany = async (event) => { event.preventDefault(); setSaving('company'); try { const result = await apiRequest('/api/settings/company', { method: 'PUT', headers, body: JSON.stringify(company) }); setCompany({ ...defaultCompany, ...result.company }); notify('Tashkilot sozlamalari yangilandi.'); } catch (error) { notify(error.message); } finally { setSaving(''); } };

  const tabs = [{ id: 'profile', label: 'Profil', icon: UserRound }, { id: 'notifications', label: 'Bildirishnomalar', icon: Bell }, { id: 'security', label: 'Xavfsizlik', icon: ShieldCheck }, ...(canManage ? [{ id: 'company', label: 'Tashkilot', icon: Building2 }, { id: 'system', label: 'Tizim', icon: MonitorCog }] : [])];

  return <div className="settings-page"><div className="page-heading"><div><h1>Sozlamalar</h1><p>Profil, xavfsizlik, bildirishnoma va tizim parametrlarini boshqaring</p></div></div><div className="settings-layout"><aside className="settings-nav">{tabs.map(({ id, label, icon: Icon }) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}><Icon size={18} /><span>{label}</span></button>)}</aside><section className="settings-content">
    {tab === 'profile' && <form className="settings-card" onSubmit={saveProfile}><header><span><UserRound size={21} /></span><div><h2>Shaxsiy profil</h2><p>Panelda ko‘rinadigan ma’lumotlaringiz</p></div></header><div className="profile-settings-head"><div className="settings-avatar">{profile.avatarUrl ? <img src={profile.avatarUrl} alt="Profil" /> : initials(profile.fullName)}</div><div><strong>{profile.fullName || 'Foydalanuvchi'}</strong><small>@{profile.login} · {session.user.role}</small></div></div><div className="form-grid"><label className="form-field"><span>To‘liq ism</span><input value={profile.fullName} onChange={(event) => setProfile((current) => ({ ...current, fullName: event.target.value }))} required /></label><label className="form-field"><span>Login</span><input value={profile.login} disabled /></label><label className="form-field"><span>Telefon</span><input value={profile.phone || ''} onChange={(event) => setProfile((current) => ({ ...current, phone: event.target.value }))} placeholder="+998..." /></label><label className="form-field"><span>Email</span><input type="email" value={profile.email || ''} onChange={(event) => setProfile((current) => ({ ...current, email: event.target.value }))} placeholder="name@aloo.uz" /></label><label className="form-field"><span>Lavozim</span><input value={profile.jobTitle || ''} onChange={(event) => setProfile((current) => ({ ...current, jobTitle: event.target.value }))} /></label><label className="form-field"><span>Telegram</span><input value={profile.telegramUsername || ''} onChange={(event) => setProfile((current) => ({ ...current, telegramUsername: event.target.value }))} placeholder="@username" /></label><label className="form-field form-field--full"><span>Avatar URL</span><input value={profile.avatarUrl || ''} onChange={(event) => setProfile((current) => ({ ...current, avatarUrl: event.target.value }))} placeholder="https://..." /></label></div><footer><button className="button-primary" disabled={saving === 'profile'}><Save size={17} /> {saving === 'profile' ? 'Saqlanmoqda...' : 'Profilni saqlash'}</button></footer></form>}
    {tab === 'notifications' && <div className="settings-card"><header><span><Bell size={21} /></span><div><h2>Bildirishnomalar</h2><p>Qaysi voqealar haqida xabar olishingizni tanlang</p></div></header><div className="settings-section"><h3>Bildirishnoma kanallari</h3><Toggle checked={prefs.desktopEnabled} onChange={(value) => setPrefs((current) => ({ ...current, desktopEnabled: value }))} label="Panel bildirishnomalari" description="Yangi voqealarni yuqori panelda ko‘rsatish" /><Toggle checked={prefs.soundEnabled} onChange={(value) => setPrefs((current) => ({ ...current, soundEnabled: value }))} label="Xabar ovozi" description="Yangi chat va muhim voqealarda ovoz" /></div><div className="settings-section"><h3>Voqea turlari</h3><Toggle checked={prefs.chatNotifications} onChange={(value) => setPrefs((current) => ({ ...current, chatNotifications: value }))} label="Chat xabarlari" description="Shaxsiy va guruh chatlaridagi yangi xabarlar" /><Toggle checked={prefs.taskNotifications} onChange={(value) => setPrefs((current) => ({ ...current, taskNotifications: value }))} label="Vazifalar" description="Yangi vazifa, status va deadline o‘zgarishlari" /><Toggle checked={prefs.contentNotifications} onChange={(value) => setPrefs((current) => ({ ...current, contentNotifications: value }))} label="Kontent" description="Tekshiruv, tasdiq va nashr holatlari" /><Toggle checked={prefs.expenseNotifications} onChange={(value) => setPrefs((current) => ({ ...current, expenseNotifications: value }))} label="Xarajatlar" description="Tasdiqlash, rad etish va to‘lov holatlari" /><Toggle checked={prefs.reportNotifications} onChange={(value) => setPrefs((current) => ({ ...current, reportNotifications: value }))} label="Hisobotlar" description="Hisobot tayyor bo‘lganda xabar berish" /></div><footer><button className="button-primary" onClick={savePrefs} disabled={saving === 'prefs'}><Save size={17} /> {saving === 'prefs' ? 'Saqlanmoqda...' : 'Sozlamalarni saqlash'}</button></footer></div>}
    {tab === 'security' && <form className="settings-card" onSubmit={savePassword}><header><span><KeyRound size={21} /></span><div><h2>Parolni yangilash</h2><p>Hisobingiz xavfsizligi uchun kuchli parol ishlating</p></div></header><div className="security-note"><ShieldCheck size={20} /><div><strong>Xavfsizlik tavsiyasi</strong><p>Kamida 10 ta belgi, katta-kichik harf va raqamdan foydalaning.</p></div></div><div className="form-grid form-grid--single">{[['currentPassword','Joriy parol'],['newPassword','Yangi parol'],['confirmPassword','Yangi parolni takrorlang']].map(([key,label]) => <label className="form-field" key={key}><span>{label}</span><div className="password-field"><input type={showPasswords ? 'text' : 'password'} value={password[key]} onChange={(event) => setPassword((current) => ({ ...current, [key]: event.target.value }))} minLength={6} required /><button type="button" onClick={() => setShowPasswords((value) => !value)}>{showPasswords ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></label>)}</div><footer><button className="button-primary" disabled={saving === 'password'}><KeyRound size={17} /> {saving === 'password' ? 'Yangilanmoqda...' : 'Parolni yangilash'}</button></footer></form>}
    {tab === 'company' && <form className="settings-card" onSubmit={saveCompany}><header><span><Building2 size={21} /></span><div><h2>Tashkilot sozlamalari</h2><p>Aloo panelining umumiy parametrlari</p></div></header><div className="form-grid"><label className="form-field"><span>Tizim nomi</span><input value={company.companyName} onChange={(event) => setCompany((current) => ({ ...current, companyName: event.target.value }))} required /></label><label className="form-field"><span>Domen</span><input value={company.domain} onChange={(event) => setCompany((current) => ({ ...current, domain: event.target.value }))} /></label><label className="form-field"><span>Yordam telefoni</span><input value={company.supportPhone} onChange={(event) => setCompany((current) => ({ ...current, supportPhone: event.target.value }))} /></label><label className="form-field"><span>Yordam Telegram</span><input value={company.supportTelegram} onChange={(event) => setCompany((current) => ({ ...current, supportTelegram: event.target.value }))} /></label><label className="form-field"><span>Vaqt zonasi</span><select value={company.timezone} onChange={(event) => setCompany((current) => ({ ...current, timezone: event.target.value }))}><option value="Asia/Tashkent">Asia/Tashkent</option><option value="Europe/Istanbul">Europe/Istanbul</option><option value="UTC">UTC</option></select></label><label className="form-field"><span>Valyuta</span><select value={company.currency} onChange={(event) => setCompany((current) => ({ ...current, currency: event.target.value }))}><option value="UZS">UZS — so‘m</option><option value="USD">USD — dollar</option><option value="TRY">TRY — lira</option></select></label><label className="form-field"><span>Asosiy til</span><select value={company.defaultLanguage} onChange={(event) => setCompany((current) => ({ ...current, defaultLanguage: event.target.value }))}><option value="uz">O‘zbekcha</option><option value="ru">Русский</option><option value="en">English</option></select></label><label className="form-field"><span>Brend rangi</span><div className="color-field"><input type="color" value={company.brandColor} onChange={(event) => setCompany((current) => ({ ...current, brandColor: event.target.value }))} /><input value={company.brandColor} onChange={(event) => setCompany((current) => ({ ...current, brandColor: event.target.value }))} /></div></label></div><footer><button className="button-primary" disabled={saving === 'company'}><Save size={17} /> {saving === 'company' ? 'Saqlanmoqda...' : 'Tashkilotni saqlash'}</button></footer></form>}
    {tab === 'system' && <div className="settings-card"><header><span><MonitorCog size={21} /></span><div><h2>Tizim holati</h2><p>Versiya va ma’lumotlar bazasi statistikasi</p></div></header>{system && <><div className="system-status"><span><Check size={18} /></span><div><strong>Tizim normal ishlamoqda</strong><p>Backend, PostgreSQL va frontend xizmatlari faol</p></div></div><div className="system-grid"><article><small>Panel versiyasi</small><strong>v{system.version}</strong><p>Step 8</p></article><article><small>Ma’lumotlar bazasi</small><strong>{system.database}</strong><p>{system.runtime}</p></article><article><small>Foydalanuvchilar</small><strong>{system.stats?.users || 0}</strong><p>{system.stats?.branches || 0} filial</p></article><article><small>Kontent</small><strong>{system.stats?.content_items || 0}</strong><p>{system.stats?.media_assets || 0} media</p></article><article><small>Chat xabarlari</small><strong>{system.stats?.chat_messages || 0}</strong><p>saqlangan xabar</p></article></div></>}</div>}
  </section></div></div>;
}
